# global config
global:
  scrape_interval:     30s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 30s # Evaluate rules every 15 seconds. The default is every 1 minute.

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: "self"
    static_configs:
      - targets: ['localhost:9090'] # the address of an application that exposes metrics for prometheus
  - job_name: "meme.garden"
    scrape_interval: 15s
    static_configs:
      - targets: ['meme.garden:9100'] # the address of an application that exposes metrics for prometheus
